services:
  app:
    build: .
    container_name: it-ticketing-app
    ports:
      - "8080:3000"
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
