// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2026, 1:30:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/adhinath/Project/it-ticketing-&-work-monitoring/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/plugins/**/*.{js,ts,mjs}","/home/adhinath/Project/it-ticketing-&-work-monitoring/composables/**/*.{js,ts,mjs}","/home/adhinath/Project/it-ticketing-&-work-monitoring/utils/**/*.{js,ts,mjs}","/home/adhinath/Project/it-ticketing-&-work-monitoring/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/home/adhinath/Project/it-ticketing-&-work-monitoring/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;