import type { AppUser, CategoryItem, TechnicianItem, Ticket, VendorItem } from '~/types';

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'USR-001',
    name: 'Rina Wulandari',
    email: 'rina.wulandari@company.co.id',
    role: 'USER_NON_IT',
    department: 'Finance & Accounting',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'IT-001',
    name: 'Budi Santoso',
    email: 'budi.santoso@it.company.co.id',
    role: 'IT_WORKER',
    department: 'IT Support & Hardware',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'IT-002',
    name: 'Andi Pratama',
    email: 'andi.pratama@it.company.co.id',
    role: 'IT_WORKER',
    department: 'Software Engineering',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'IT-003',
    name: 'Dedi Kurniawan',
    email: 'dedi.kurniawan@it.company.co.id',
    role: 'IT_WORKER',
    department: 'Network & Infrastructure',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'IT-004',
    name: 'Rizal Siregar',
    email: 'rizal.siregar@it.company.co.id',
    role: 'IT_WORKER',
    department: 'DevOps & Database',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'ADMIN-001',
    name: 'Administrator IT',
    email: 'sysadmin@company.co.id',
    role: 'SYSTEM_ADMIN',
    department: 'Enterprise IT Governance',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'CAT-01',
    name: 'Hardware',
    subcategories: ['Printer', 'Scanner', 'Laptop', 'PC Desktop', 'Monitor', 'Mouse & Keyboard'],
  },
  {
    id: 'CAT-02',
    name: 'Software & Aplikasi',
    subcategories: ['SAP ERP', 'Office 365', 'Email Outlook', 'Web Portal Internal', 'Browser / VPN Client'],
  },
  {
    id: 'CAT-03',
    name: 'Jaringan & Koneksi',
    subcategories: ['Wifi Kantor', 'Kabel LAN Meja', 'Akses Internet Drop', 'Koneksi Server Lokal'],
  },
  {
    id: 'CAT-04',
    name: 'Akun & Keamanan',
    subcategories: ['Reset Password', 'Permintaan Akun Baru', 'Izin Akses Shared Folder', 'Autentikasi 2FA'],
  },
  {
    id: 'CAT-05',
    name: 'Infrastruktur & Server',
    subcategories: ['Database Maintenance', 'Server High Load', 'Backup & Restore', 'Virtual Machine'],
  },
];

export const INITIAL_VENDORS: VendorItem[] = [
  {
    id: 'VND-01',
    name: 'PT Mitra Solusi Printer',
    service_type: 'Perbaikan Printer, Mesin Fotokopi, dan Suplai Toner',
    contact_person: 'Pak Bambang Sudibyo',
    phone: '0812-9988-7711',
  },
  {
    id: 'VND-02',
    name: 'PT Telkom Akses Prima',
    service_type: 'Infrastruktur Fiber Optic, Backbone Internet, Router Cisco',
    contact_person: 'Ibu Ratna Dewi',
    phone: '0811-3322-1144',
  },
  {
    id: 'VND-03',
    name: 'CV Sentra Servis Komputer',
    service_type: 'Pergantian Motherboard, Reballing Chipset, Panel LCD',
    contact_person: 'Pak Dimas Anggoro',
    phone: '0813-5566-7788',
  },
];

export const INITIAL_TECHNICIANS: TechnicianItem[] = [
  {
    id: 'TEK-01',
    name: 'Pak Joko Susanto',
    specialty: 'Teknisi Listrik Gedung & Crimping Kabel UTP',
    phone: '0878-1122-3344',
  },
  {
    id: 'TEK-02',
    name: 'Mas Fajar Nugroho',
    specialty: 'Teknisi PABX & Setting Telepon Meja',
    phone: '0896-4455-6677',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'TCK-202609-001',
    title: 'Printer Lantai 2 Kehabisan Tinta & Paper Jam Parah',
    description: 'Printer EPSON L3150 di divisi Keuangan Lantai 2 tidak dapat mencetak invoice akhir bulan. Ada kertas tersangkut dan lampu indikator tinta berkedip merah terus menerus.',
    category: 'Hardware',
    subcategory: 'Printer',
    location: 'Gedung A, Lantai 2 - Ruang Finance',
    priority: 'HIGH',
    status: 'PROCESS',
    created_by: 'USR-001',
    requestedBy: 'USR-001',
    requestedByName: 'Rina Wulandari',
    requestedByDept: 'Finance & Accounting',
    created_by_name: 'Rina Wulandari',
    created_by_dept: 'Finance & Accounting',
    primary_worker_id: 'IT-001',
    primary_worker_name: 'Budi Santoso',
    supporting_members: ['Andi Pratama', 'Dedi Kurniawan'],
    supporting_member_details: [
      { id: 'IT-002', name: 'Andi Pratama' },
      { id: 'IT-003', name: 'Dedi Kurniawan' },
    ],
    delegation: null,
    referenced_ticket_id: null,
    created_at: '2026-09-11T09:00:00Z',
    issued_at: '2026-09-11T09:05:00Z',
    process_started_at: '2026-09-11T09:15:00Z',
    completed_at: null,
    attachments: [
      {
        id: 'ATT-001',
        stage: 'REQUEST',
        visibility: 'USER_VISIBLE',
        file_name: 'foto_printer_berkedip_merah.jpg',
        file_size: '2.4 MB',
        uploaded_by: 'USR-001',
        uploaded_by_name: 'Rina Wulandari',
        uploaded_at: '2026-09-11T09:02:00Z',
      },
      {
        id: 'ATT-002',
        stage: 'IN_PROGRESS',
        visibility: 'INTERNAL_ONLY',
        file_name: 'log_roller_printer_sensor.txt',
        file_size: '45 KB',
        uploaded_by: 'IT-001',
        uploaded_by_name: 'Budi Santoso',
        uploaded_at: '2026-09-11T09:40:00Z',
      },
      {
        id: 'ATT-003',
        stage: 'IN_PROGRESS',
        visibility: 'USER_VISIBLE',
        file_name: 'foto_proses_pembersihan_roller.jpg',
        file_size: '1.8 MB',
        uploaded_by: 'IT-001',
        uploaded_by_name: 'Budi Santoso',
        uploaded_at: '2026-09-11T10:00:00Z',
      },
    ],
    worklogs: [
      {
        id: 'WL-001',
        stageKey: 'IN_PROGRESS',
        worker_id: 'IT-001',
        worker_name: 'Budi Santoso',
        date: '2026-09-11',
        start_at: '09:15',
        finish_at: '09:45',
        duration_minutes: 30,
        description: 'Pengecekan fisik printer di lantai 2. Ditemukan serpihan kertas sobek di dalam gear roller penarik kertas.',
        created_at: '2026-09-11T09:45:00Z',
      },
      {
        id: 'WL-002',
        stageKey: 'IN_PROGRESS',
        worker_id: 'IT-001',
        worker_name: 'Budi Santoso',
        date: '2026-09-11',
        start_at: '09:50',
        finish_at: '10:30',
        duration_minutes: 40,
        description: 'Pembongkaran casing penutup roller, pembersihan debu, dan penyedotan sisa kertas sobek dengan vacuum mini IT.',
        created_at: '2026-09-11T10:30:00Z',
      },
    ],
    comments: [
      {
        id: 'CMT-001',
        user_id: 'USR-001',
        user_name: 'Rina Wulandari',
        user_role: 'USER_NON_IT',
        message: 'Selamat pagi Mas Budi, mohon dibantu ya karena berkas pajak harus dicetak sebelum jam 1 siang.',
        created_at: '2026-09-11T09:20:00Z',
      },
      {
        id: 'CMT-002',
        user_id: 'IT-001',
        user_name: 'Budi Santoso',
        user_role: 'IT_WORKER',
        message: 'Siap Bu Rina, sedang kami bersihkan rollernya dan segera isi ulang tinta hitam.',
        created_at: '2026-09-11T09:35:00Z',
      },
    ],
    internal_notes: [
      {
        id: 'IN-001',
        author_id: 'IT-001',
        author_name: 'Budi Santoso',
        note: 'Sensor head printing agak miring. Jika setelah direset masih error, eskalasi ke Vendor PT Mitra Solusi Printer untuk ganti sparepart karet penarik.',
        created_at: '2026-09-11T09:42:00Z',
      },
    ],
    audit_logs: [
      {
        id: 'AUD-001',
        performed_at: '2026-09-11T09:00:00Z',
        performed_by: 'USR-001',
        performed_by_name: 'Rina Wulandari',
        action: 'Draft Tiket Dibuat',
        notes: 'User mengisi form kendala printer lantai 2.',
      },
      {
        id: 'AUD-002',
        performed_at: '2026-09-11T09:05:00Z',
        performed_by: 'USR-001',
        performed_by_name: 'Rina Wulandari',
        action: 'Issue Tiket ke Antrean IT',
        notes: 'Tiket resmi masuk ke pool antrean IT.',
      },
      {
        id: 'AUD-003',
        performed_at: '2026-09-11T09:12:00Z',
        performed_by: 'IT-001',
        performed_by_name: 'Budi Santoso',
        action: 'Ambil Tiket (Take Ticket)',
        notes: 'Budi Santoso mengambil tiket sebagai Primary Worker.',
      },
      {
        id: 'AUD-004',
        performed_at: '2026-09-11T09:15:00Z',
        performed_by: 'IT-001',
        performed_by_name: 'Budi Santoso',
        action: 'Mulai Pengerjaan (Status -> PROCESS)',
        notes: 'Pengerjaan dimulai di lokasi pemohon.',
      },
      {
        id: 'AUD-005',
        performed_at: '2026-09-11T09:30:00Z',
        performed_by: 'IT-001',
        performed_by_name: 'Budi Santoso',
        action: 'Tambah Supporting Member',
        notes: 'Menambahkan Andi Pratama dan Dedi Kurniawan untuk backup penanganan.',
      },
    ],
  },
  {
    id: 'TCK-202609-002',
    title: 'Gagal Login Akun ERP SAP Keuangan (User Locked)',
    description: 'Muncul error pesan "User account locked due to 3 incorrect password attempts". Tidak bisa approval batch vendor.',
    category: 'Software & Aplikasi',
    subcategory: 'SAP ERP',
    location: 'Gedung A, Lantai 3 - Akuntansi',
    priority: 'CRITICAL',
    status: 'SELESAI',
    created_by: 'USR-001',
    requestedBy: 'USR-001',
    requestedByName: 'Rina Wulandari',
    requestedByDept: 'Finance & Accounting',
    created_by_name: 'Rina Wulandari',
    created_by_dept: 'Finance & Accounting',
    primary_worker_id: 'IT-002',
    primary_worker_name: 'Andi Pratama',
    supporting_members: ['Rizal Siregar'],
    supporting_member_details: [{ id: 'IT-004', name: 'Rizal Siregar' }],
    delegation: null,
    referenced_ticket_id: null,
    created_at: '2026-09-10T14:00:00Z',
    issued_at: '2026-09-10T14:02:00Z',
    process_started_at: '2026-09-10T14:10:00Z',
    completed_at: '2026-09-10T14:45:00Z',
    resolution_summary: 'Unlock user melalui SAP Transaction Code SU01, reset temporary password, dan verifikasi login bersama user via remote desktop.',
    confirmed_by_user: true,
    attachments: [
      {
        id: 'ATT-004',
        stage: 'REQUEST',
        visibility: 'USER_VISIBLE',
        file_name: 'screenshot_sap_locked_screen.png',
        file_size: '480 KB',
        uploaded_by: 'USR-001',
        uploaded_by_name: 'Rina Wulandari',
        uploaded_at: '2026-09-10T14:01:00Z',
      },
      {
        id: 'ATT-005',
        stage: 'COMPLETION',
        visibility: 'USER_VISIBLE',
        file_name: 'bukti_login_sap_berhasil.png',
        file_size: '620 KB',
        uploaded_by: 'IT-002',
        uploaded_by_name: 'Andi Pratama',
        uploaded_at: '2026-09-10T14:44:00Z',
      },
    ],
    worklogs: [
      {
        id: 'WL-003',
        stageKey: 'IN_PROGRESS',
        worker_id: 'IT-002',
        worker_name: 'Andi Pratama',
        date: '2026-09-10',
        start_at: '14:10',
        finish_at: '14:45',
        duration_minutes: 35,
        description: 'Buka SAP GUI server dev/prod, cek status user di SU01, uncheck lock flag, buat password sementara, dan dampingi user login ulang.',
        created_at: '2026-09-10T14:45:00Z',
      },
    ],
    comments: [
      {
        id: 'CMT-003',
        user_id: 'IT-002',
        user_name: 'Andi Pratama',
        user_role: 'IT_WORKER',
        message: 'Password sementara sudah dikirim via WhatsApp dinas. Silakan dicoba login kembali Bu Rina.',
        created_at: '2026-09-10T14:35:00Z',
      },
      {
        id: 'CMT-004',
        user_id: 'USR-001',
        user_name: 'Rina Wulandari',
        user_role: 'USER_NON_IT',
        message: 'Terima kasih banyak Mas Andi, sudah bisa masuk kembali dan batch approval selesai.',
        created_at: '2026-09-10T14:46:00Z',
      },
    ],
    internal_notes: [],
    audit_logs: [
      {
        id: 'AUD-006',
        performed_at: '2026-09-10T14:00:00Z',
        performed_by: 'USR-001',
        performed_by_name: 'Rina Wulandari',
        action: 'Tiket Dibuat & Di-issue',
        notes: 'Prioritas Critical karena deadline closing.',
      },
      {
        id: 'AUD-007',
        performed_at: '2026-09-10T14:10:00Z',
        performed_by: 'IT-002',
        performed_by_name: 'Andi Pratama',
        action: 'Tiket Diambil & Diproses',
        notes: 'Direct remote desktop assist.',
      },
      {
        id: 'AUD-008',
        performed_at: '2026-09-10T14:45:00Z',
        performed_by: 'IT-002',
        performed_by_name: 'Andi Pratama',
        action: 'Tiket Selesai (SELESAI)',
        notes: 'Supporting members dan assignment terkunci secara permanen.',
      },
    ],
  },
  {
    id: 'TCK-202609-003',
    title: 'Koneksi Wifi Ruang Rapat Direksi Drop Berulang Kali',
    description: 'Access Point Aruba di Ruang Rapat Direksi Lantai 5 sering disconnect mendadak saat video conference Zoom board meeting.',
    category: 'Jaringan & Koneksi',
    subcategory: 'Wifi Kantor',
    location: 'Gedung Utama, Lantai 5 - Boardroom',
    priority: 'HIGH',
    status: 'DELEGASI',
    created_by: 'USR-001',
    created_by_name: 'Rina Wulandari',
    created_by_dept: 'Sekretariat Direksi',
    primary_worker_id: 'IT-003',
    primary_worker_name: 'Dedi Kurniawan',
    supporting_members: ['Budi Santoso'],
    supporting_member_details: [{ id: 'IT-001', name: 'Budi Santoso' }],
    delegation: {
      type: 'DELEGASI_VENDOR',
      vendor_id: 'VND-02',
      vendor_name: 'PT Telkom Akses Prima',
      reference_no: 'TLK-WO-2026-8821',
      notes: 'Pemeriksaan kabel FO uplink dan kalibrasi power sinyal Access Point enterprise.',
      delegated_at: '2026-09-11T11:00:00Z',
    },
    referenced_ticket_id: null,
    created_at: '2026-09-11T08:30:00Z',
    issued_at: '2026-09-11T08:35:00Z',
    process_started_at: '2026-09-11T09:00:00Z',
    completed_at: null,
    attachments: [
      {
        id: 'ATT-006',
        stage: 'REQUEST',
        visibility: 'USER_VISIBLE',
        file_name: 'foto_access_point_plafon.jpg',
        file_size: '3.1 MB',
        uploaded_by: 'USR-001',
        uploaded_by_name: 'Rina Wulandari',
        uploaded_at: '2026-09-11T08:32:00Z',
      },
      {
        id: 'ATT-007',
        stage: 'IN_PROGRESS',
        visibility: 'INTERNAL_ONLY',
        file_name: 'wireshark_packet_loss_log.pcap',
        file_size: '12.5 MB',
        uploaded_by: 'IT-003',
        uploaded_by_name: 'Dedi Kurniawan',
        uploaded_at: '2026-09-11T10:15:00Z',
      },
      {
        id: 'ATT-008',
        stage: 'DELEGATION',
        visibility: 'USER_VISIBLE',
        file_name: 'form_serah_terima_vendor_telkom.pdf',
        file_size: '1.1 MB',
        uploaded_by: 'IT-003',
        uploaded_by_name: 'Dedi Kurniawan',
        uploaded_at: '2026-09-11T11:05:00Z',
      },
    ],
    worklogs: [
      {
        id: 'WL-004',
        stageKey: 'IN_PROGRESS',
        worker_id: 'IT-003',
        worker_name: 'Dedi Kurniawan',
        date: '2026-09-11',
        start_at: '09:00',
        finish_at: '10:30',
        duration_minutes: 90,
        description: 'Cek channel interference dan ping gateway. Ditemukan packet loss 18% pada switch uplink lantai 5.',
        created_at: '2026-09-11T10:30:00Z',
      },
    ],
    comments: [
      {
        id: 'CMT-005',
        user_id: 'IT-003',
        user_name: 'Dedi Kurniawan',
        user_role: 'IT_WORKER',
        message: 'Tiket sementara didelegasikan ke vendor PT Telkom Akses Prima untuk penggantian modul SFP optik di switch rack.',
        created_at: '2026-09-11T11:10:00Z',
      },
    ],
    internal_notes: [
      {
        id: 'IN-002',
        author_id: 'IT-003',
        author_name: 'Dedi Kurniawan',
        note: 'Garansi SLA vendor Telkom adalah 4 jam kerja. Follow up jam 14.00 jika teknisi belum tiba di lokasi.',
        created_at: '2026-09-11T11:02:00Z',
      },
    ],
    audit_logs: [
      {
        id: 'AUD-009',
        performed_at: '2026-09-11T08:35:00Z',
        performed_by: 'USR-001',
        performed_by_name: 'Rina Wulandari',
        action: 'Tiket Di-issue',
        notes: 'Antrean Jaringan.',
      },
      {
        id: 'AUD-010',
        performed_at: '2026-09-11T09:00:00Z',
        performed_by: 'IT-003',
        performed_by_name: 'Dedi Kurniawan',
        action: 'Mulai Analisa Jaringan',
        notes: 'Testing throughput.',
      },
      {
        id: 'AUD-011',
        performed_at: '2026-09-11T11:00:00Z',
        performed_by: 'IT-003',
        performed_by_name: 'Dedi Kurniawan',
        action: 'Delegasikan ke Vendor (DELEGASI_VENDOR)',
        notes: 'Didelegasikan ke PT Telkom Akses Prima (Ref: TLK-WO-2026-8821).',
      },
    ],
  },
  {
    id: 'TCK-202609-004',
    title: 'Request Lisensi & Instalasi Software Figma Professional',
    description: 'Permintaan lisensi figma untuk 2 staff UI/UX baru serta instalasi font korporat.',
    category: 'Software & Aplikasi',
    subcategory: 'Web Portal Internal',
    location: 'Gedung B, Lantai 4 - Tim Desain',
    priority: 'LOW',
    status: 'DRAFT',
    created_by: 'USR-001',
    created_by_name: 'Rina Wulandari',
    created_by_dept: 'HR & GA Team',
    primary_worker_id: null,
    primary_worker_name: null,
    supporting_members: [],
    delegation: null,
    referenced_ticket_id: null,
    created_at: '2026-09-11T11:30:00Z',
    issued_at: null,
    process_started_at: null,
    completed_at: null,
    attachments: [
      {
        id: 'ATT-009',
        stage: 'REQUEST',
        visibility: 'USER_VISIBLE',
        file_name: 'memo_persetujuan_kadiv.pdf',
        file_size: '350 KB',
        uploaded_by: 'USR-001',
        uploaded_by_name: 'Rina Wulandari',
        uploaded_at: '2026-09-11T11:32:00Z',
      },
    ],
    worklogs: [],
    comments: [],
    internal_notes: [],
    audit_logs: [
      {
        action: 'TIKET_DRAFT_DISIMPAN',
        performed_at: '2026-09-11T09:00:00Z',
        performed_by: 'USR-001',
        performed_by_name: 'Rina Wulandari',
      }
    ],
  },
  {
    id: 'TCK-202609-005',
    title: 'Server Database Payroll High CPU & Memory Spike > 95%',
    description: 'Alert monitoring Zabbix: Server DB-PAYROLL-01 utilisasi memory 96% dan query lock timeout pada perhitungan lembur bulanan.',
    category: 'Infrastruktur & Server',
    subcategory: 'Database Maintenance',
    location: 'Data Center Lt 1 - Server Room A',
    priority: 'CRITICAL',
    status: 'PROCESS',
    created_by: 'IT-LEAD',
    created_by_name: 'Hendra Wijaya',
    created_by_dept: 'IT Lead',
    primary_worker_id: 'IT-004',
    primary_worker_name: 'Rizal Siregar',
    supporting_members: ['Andi Pratama'],
    supporting_member_details: [{ id: 'IT-002', name: 'Andi Pratama' }],
    delegation: null,
    referenced_ticket_id: null,
    created_at: '2026-09-11T07:45:00Z',
    issued_at: '2026-09-11T07:46:00Z',
    process_started_at: '2026-09-11T08:00:00Z',
    completed_at: null,
    attachments: [
      {
        id: 'ATT-010',
        stage: 'IN_PROGRESS',
        visibility: 'INTERNAL_ONLY',
        file_name: 'slow_query_explain_analyze.log',
        file_size: '88 KB',
        uploaded_by: 'IT-004',
        uploaded_by_name: 'Rizal Siregar',
        uploaded_at: '2026-09-11T08:20:00Z',
      },
    ],
    worklogs: [
      {
        id: 'WL-005',
        stageKey: 'IN_PROGRESS',
        worker_id: 'IT-004',
        worker_name: 'Rizal Siregar',
        date: '2026-09-11',
        start_at: '08:00',
        finish_at: '09:15',
        duration_minutes: 75,
        description: 'Kill blocked transactions pada pg_stat_activity, rebuild index tabel payroll_transactions, dan setting vacuum parameter.',
        created_at: '2026-09-11T09:15:00Z',
      },
    ],
    comments: [],
    internal_notes: [
      {
        id: 'IN-003',
        author_id: 'IT-004',
        author_name: 'Rizal Siregar',
        note: 'Indeks tabel overtime missing composite key pada timestamp dan employee_id. Diskusi dengan developer ERP siang ini.',
        created_at: '2026-09-11T08:45:00Z',
      },
    ],
    audit_logs: [
      {
        id: 'AUD-013',
        performed_at: '2026-09-11T07:45:00Z',
        performed_by: 'IT-LEAD',
        performed_by_name: 'Hendra Wijaya',
        action: 'Tiket Dibuat & Assigned ke Rizal Siregar',
        notes: 'SLA penanganan 15 menit.',
      },
      {
        id: 'AUD-014',
        performed_at: '2026-09-11T08:00:00Z',
        performed_by: 'IT-004',
        performed_by_name: 'Rizal Siregar',
        action: 'Mulai Optimasi Database',
        notes: 'Investigasi pg_stat_activity.',
      },
    ],
  },
  {
    id: 'TCK-202609-006',
    title: 'Monitor PC Kasir Toko Bergaris Vertikal & Berkedip',
    description: 'Monitor Dell 24 inch pada meja kasir front-office bergaris hijau vertikal saat dinyalakan.',
    category: 'Hardware',
    subcategory: 'Monitor',
    location: 'Cabang Thamrin - Front Desk',
    priority: 'MEDIUM',
    status: 'SELESAI',
    created_by: 'USR-001',
    created_by_name: 'Rina Wulandari',
    created_by_dept: 'Operasional Cabang',
    primary_worker_id: 'IT-001',
    primary_worker_name: 'Budi Santoso',
    supporting_members: [],
    delegation: null,
    referenced_ticket_id: null,
    created_at: '2026-09-09T10:00:00Z',
    issued_at: '2026-09-09T10:05:00Z',
    process_started_at: '2026-09-09T10:30:00Z',
    completed_at: '2026-09-09T11:45:00Z',
    resolution_summary: 'Penggantian kabel HDMI yang longgar dan update display driver graphics Intel UHD.',
    confirmed_by_user: true,
    attachments: [
      {
        id: 'ATT-011',
        stage: 'REQUEST',
        visibility: 'USER_VISIBLE',
        file_name: 'foto_monitor_garis_hijau.jpg',
        file_size: '1.9 MB',
        uploaded_by: 'USR-001',
        uploaded_by_name: 'Rina Wulandari',
        uploaded_at: '2026-09-09T10:03:00Z',
      },
      {
        id: 'ATT-012',
        stage: 'COMPLETION',
        visibility: 'USER_VISIBLE',
        file_name: 'foto_monitor_normal_setelah_perbaikan.jpg',
        file_size: '2.1 MB',
        uploaded_by: 'IT-001',
        uploaded_by_name: 'Budi Santoso',
        uploaded_at: '2026-09-09T11:40:00Z',
      },
    ],
    worklogs: [
      {
        id: 'WL-006',
        stageKey: 'IN_PROGRESS',
        worker_id: 'IT-001',
        worker_name: 'Budi Santoso',
        date: '2026-09-09',
        start_at: '10:30',
        finish_at: '11:45',
        duration_minutes: 75,
        description: 'Test kabel monitor dengan kabel baru, install update driver, dan soak test selama 30 menit.',
        created_at: '2026-09-09T11:45:00Z',
      },
    ],
    comments: [],
    internal_notes: [],
    audit_logs: [
      {
        id: 'AUD-015',
        performed_at: '2026-09-09T10:00:00Z',
        performed_by: 'USR-001',
        performed_by_name: 'Rina Wulandari',
        action: 'Tiket Dibuat',
        notes: 'Hardware issue.',
      },
      {
        id: 'AUD-016',
        performed_at: '2026-09-09T11:45:00Z',
        performed_by: 'IT-001',
        performed_by_name: 'Budi Santoso',
        action: 'Pekerjaan Selesai (SELESAI)',
        notes: 'Ganti kabel HDMI baru dari inventaris IT.',
      },
    ],
  },
];
